# Generated by Django 4.0.4 on 2022-05-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpro', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=150)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
